module.exports = {
  parser: "@typescript-eslint/parser",
  extends: ["plugin:@typescript-eslint/recommended", "prettier"],
  rules: {
    "import/no-unused-modules": "error",
    "import/export": "error",
    eqeqeq: "error",
    "no-extra-bind": "error",
    "no-throw-literal": "error",
    yoda: ["error", "never", { onlyEquality: true }],
    "max-depth": ["error", 6],
    "max-len": ["error", 120],
    "max-nested-callbacks": ["error", 3],
    "max-params": ["error", 6],
    "no-lonely-if": "error",
    "no-var": "error",
    "one-var-declaration-per-line": ["error", "always"],
    "one-var": ["error", "never"],
    complexity: ["error", 20],

    "no-shadow": "warn",
    "no-return-await": "warn",
    "no-useless-return": "warn",
    "prefer-spread": "warn",
    "prefer-rest-params": "warn",
    "no-warning-comments": "warn",
    "no-console": "warn",
    "guard-for-in": "warn",
    "no-sequences": "warn",
    "no-else-return": "warn",
    "prefer-arrow-callback": "warn",
    "prefer-template": "warn",
    "import/no-duplicates": "warn",
    "import/first": "warn",
    "jsx-quotes": ["warn", "prefer-single"],
    "@typescript-eslint/quotes": [
      "error",
      "single",
      {
        avoidEscape: true,
        allowTemplateLiterals: true,
      },
    ],

    // disabling these as it makes linting very slow
    "import/named": "off",
    "import/namespace": "off",
    "import/default": "off",
    "import/no-named-as-default-member": "off",
    "import/no-unresolved": "off",
    quotes: "off",

    "@typescript-eslint/default-param-last": ["error"],
    "@typescript-eslint/no-dynamic-delete": "error",
    "@typescript-eslint/consistent-type-assertions": [
      1,
      { assertionStyle: "as", objectLiteralTypeAssertions: "never" },
    ],
    "@typescript-eslint/consistent-type-definitions": ["error", "interface"],

    "@typescript-eslint/prefer-optional-chain": "warn",
    "@typescript-eslint/prefer-for-of": "warn",
    "@typescript-eslint/array-type": ["warn", { default: "array" }],
    "@typescript-eslint/prefer-reduce-type-parameter": "warn",
    "@typescript-eslint/switch-exhaustiveness-check": "warn",
    "@typescript-eslint/prefer-nullish-coalescing": "warn",
    "no-unused-expressions": "off",
    "@typescript-eslint/no-unused-expressions": "error",
    "@typescript-eslint/no-unused-vars": "warn",
    "comma-dangle": "off",
    "@typescript-eslint/comma-dangle": "off",
    "@typescript-eslint/no-misused-promises": "error",
    "@typescript-eslint/no-floating-promises": "error",
  },
  plugins: ["@typescript-eslint", "import", "i18next"],
  settings: {
    "import/resolver": {
      typescript: {},
    },
  },
  overrides: [
    {
      files: ["*.d.ts"],
      rules: {
        "max-len": "off",
      },
    },
  ],
}
